spring:
  application:
    name: haproxy-backend

haproxy:  
  port_range:
    start: 5000
    end: 7500
  
security:
  token: 
    default: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    name: X-Auth-Token
---  
spring:
  profiles: default,development
server:
  port: 8081
  
database:
  nosql:
    host: 172.16.248.144
    user: haproxy
    password: haproxy
    port: 27017
    database: haproxy

mqtt:
  host: tcp://172.16.248.160:1883
  client:
    id: haproxyhq/backend
  topic:
    prefix: /haproxyhq/agents/

haproxy:
  external_ip: 172.16.248.160

---
spring:
  profiles: cloud
server:
  port: 0

mqtt:
  host: tcp://172.24.100.35:1883
  client:
    id: haproxyhq/backend
  topic:
    prefix: /haproxyhq/agents/

haproxy:
  external_ip: 88.198.249.61

    

  